name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip repository
        run: |
          zip -r repo.zip . -x '*.git*'

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: repo.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
